/**
 * fetch-font.ts — Embed Instrument Serif (latin, woff2) for the sandbox shell.
 *
 * What it does:
 *  1. Fetches the Google Fonts css2 API with a woff2-capable UA.
 *  2. Parses out the `latin` subset woff2 URLs for regular (normal) + italic.
 *  3. Downloads both files and writes base64 data URIs to
 *     `src/lib/sandbox/font.ts` as `INSTRUMENT_SERIF_REGULAR_B64`,
 *     `INSTRUMENT_SERIF_ITALIC_B64`, plus a ready-to-embed
 *     `SANDBOX_FONT_CSS` string and a `FONT_EMBEDDED` flag.
 *
 * Usage (do NOT add an npm script — run directly):
 *   pnpm exec tsx scripts/fetch-font.ts
 *
 * Offline tolerance: if any fetch fails after 1 retry, a stub `font.ts`
 * with empty constants + `FONT_EMBEDDED = false` is written and the
 * process exits 0. The sandbox builder must then fall back to the
 * serif stack: `"Instrument Serif", ui-serif, Georgia, serif`.
 *
 * Never commit the downloaded .woff2 binaries — only the generated
 * `src/lib/sandbox/font.ts` (latin woff2 base64 is tens of KB, acceptable).
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&display=swap";

// A desktop Chrome UA forces the css2 API to return woff2 URLs.
const WOFF2_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUTPUT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "lib",
  "sandbox",
  "font.ts",
);

async function fetchWithOneRetry(
  url: string,
  init?: RequestInit,
): Promise<Response> {
  let lastError: unknown = null;
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const res = await fetch(url, init);
      if (!res.ok) {
        throw new Error(`HTTP ${res.status} ${res.statusText} for ${url}`);
      }
      return res;
    } catch (err) {
      lastError = err;
      if (attempt === 0) {
        console.warn(
          `[fetch-font] attempt ${attempt + 1} failed for ${url}, retrying once…`,
        );
      }
    }
  }
  throw lastError instanceof Error
    ? lastError
    : new Error(`fetch failed for ${url}: ${String(lastError)}`);
}

/** Extract the latin-subset woff2 URL for a given font-style from css2 text. */
function parseLatinUrl(css: string, style: "normal" | "italic"): string | null {
  // css2 returns blocks like: /* latin */ @font-face { font-style: normal; ... src: url(...) format('woff2'); }
  const blockRe =
    /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*{([^}]+)}/g;
  let match: RegExpExecArray | null;
  while ((match = blockRe.exec(css)) !== null) {
    const subset = match[1];
    const body = match[2];
    if (subset !== "latin") continue;
    const styleMatch = /font-style:\s*(normal|italic)/.exec(body);
    if (!styleMatch || styleMatch[1] !== style) continue;
    const urlMatch = /url\((https:[^)]+?\.woff2)\)/.exec(body);
    if (urlMatch) return urlMatch[1];
  }
  return null;
}

function buildFontTs(regularB64: string, italicB64: string): string {
  const header = `/**
 * AUTO-GENERATED by scripts/fetch-font.ts — do not edit by hand.
 * Instrument Serif (latin subset, woff2 as base64 data URIs) for the
 * sandboxed iframe shell (font-src data: only, no network).
 * Regenerate: pnpm exec tsx scripts/fetch-font.ts
 */
`;
  if (!regularB64 && !italicB64) {
    return `${header}
export const INSTRUMENT_SERIF_REGULAR_B64 = "";
export const INSTRUMENT_SERIF_ITALIC_B64 = "";
export const FONT_EMBEDDED: boolean = false;
export const FONT_EMBEDDED_FLAG = "FONT_EMBEDDED=false" as const;
/** Empty when the font could not be fetched (offline stub). Falls back to the serif stack. */
export const SANDBOX_FONT_CSS = "";
`;
  }
  return `${header}
export const INSTRUMENT_SERIF_REGULAR_B64 = "${regularB64}";
export const INSTRUMENT_SERIF_ITALIC_B64 = "${italicB64}";
export const FONT_EMBEDDED: boolean = true;
export const FONT_EMBEDDED_FLAG = "FONT_EMBEDDED=true" as const;
/** @font-face block for the sandbox shell. Empty string when stubbed. */
export const SANDBOX_FONT_CSS =
  "@font-face{font-family:'Instrument Serif';font-style:normal;font-weight:400;font-display:swap;src:url(data:font/woff2;base64," +
  INSTRUMENT_SERIF_REGULAR_B64 +
  ") format('woff2');}" +
  "@font-face{font-family:'Instrument Serif';font-style:italic;font-weight:400;font-display:swap;src:url(data:font/woff2;base64," +
  INSTRUMENT_SERIF_ITALIC_B64 +
  ") format('woff2');}";
`;
}

function writeStub(reason: string): void {
  console.warn(`[fetch-font] ${reason} — writing offline stub (exit 0).`);
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, buildFontTs("", ""), "utf8");
  console.log(`[fetch-font] stub written to ${OUTPUT_PATH}`);
}

async function main(): Promise<void> {
  try {
    const cssRes = await fetchWithOneRetry(CSS_URL, {
      headers: { "User-Agent": WOFF2_UA },
    });
    const css = await cssRes.text();

    const regularUrl = parseLatinUrl(css, "normal");
    const italicUrl = parseLatinUrl(css, "italic");
    if (!regularUrl || !italicUrl) {
      writeStub("could not parse latin woff2 URLs from css2 response");
      return;
    }
    console.log(`[fetch-font] regular: ${regularUrl}`);
    console.log(`[fetch-font] italic:  ${italicUrl}`);

    const [regularBuf, italicBuf] = await Promise.all([
      fetchWithOneRetry(regularUrl).then((r) => r.arrayBuffer()),
      fetchWithOneRetry(italicUrl).then((r) => r.arrayBuffer()),
    ]);
    const regularB64 = Buffer.from(regularBuf).toString("base64");
    const italicB64 = Buffer.from(italicBuf).toString("base64");
    console.log(
      `[fetch-font] downloaded ${(regularBuf.byteLength / 1024).toFixed(1)} KiB regular + ${(italicBuf.byteLength / 1024).toFixed(1)} KiB italic`,
    );

    mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
    writeFileSync(OUTPUT_PATH, buildFontTs(regularB64, italicB64), "utf8");
    console.log(`[fetch-font] wrote ${OUTPUT_PATH}`);
  } catch (err) {
    writeStub(
      err instanceof Error ? err.message : `unexpected error: ${String(err)}`,
    );
  }
}

await main();
